from glorys_plot_tools.plot_var.plot_glorys_variable import plot_glorys_variable

plot_glorys_variable(
    var='thetao',
    start_year=2019,
    start_month=6,
    start_day=26,
    lat_min=30,
    lat_max=53,
    lon_min=-80,
    lon_max=-42,
    end_year=None,
    end_month=None,
    end_day=None,
    depth_m=0,
    title=None,
    existing_fp='cmems_mod_glo_phy_my_0.083deg_P1D-m_multi-vars_80.00W-42.00W_30.00N-53.00N_0.49m_2019-06-26.nc',
    dataset_id="cmems_mod_glo_phy_my_0.083deg_P1D-m",
    dataset_version="202311",
    depth_contour=1,
    ssf_contour=1,
    gulf_stream_contour=1,
    save_path=None,
    cmap="thermal",
)